### ISSUE TITLE
Consider breaking out domain utils into a seperate library

### ISSUE THREAD

**Issue by birdsarah** [mozilla/openwpm-utils#15]
I regularly use only the domain utils portion of this library. I just noticed that `trackingprotection-tools` also does. `shavar-list-creation` in turn depends on `trackingprotection-tools`. This library has a number of heavyweight dependencies (`boto, s3fs, pyarrow, pyspark, plyvel, pandas`) which are unnecessary when you only need the domain utils. 

Admittedly, I'm philosophically opposed to unnecessary dependencies. My practical concerns include: I need cython installed unnecessarily, plyvel makes it unnecessarily not cross platform, and the general surface area for version drama is increased.

**Comment by englehardt** [comment]
I agree. We're experiencing dependency-related failures within `shavar-list-creation` because of this. I'm on board with creating a separate package that only includes the domain.py file and a reduced set of dependencies.

**Comment by birdsarah** [comment]
New package is here: https://github.com/mozilla/domain_utils/ - `pip install domain_utils`
